-- Inserir exercícios base na tabela exercise_library
INSERT INTO exercise_library (name, muscle_group, difficulty, description, equipment, duration, sets, reps, rest_time, instructions, tips)
VALUES 
  ('Supino Reto com Halteres', 'peito', 'iniciante', 'Exercício fundamental para desenvolvimento do peitoral', '["halteres", "banco"]'::jsonb, '45-60min', 3, '10-12', 60, '["Deite-se no banco com os pés apoiados no chão", "Segure os halteres na altura do peito com palmas para frente", "Empurre os halteres para cima até estender os braços", "Desça controladamente até a posição inicial"]'::jsonb, '["Mantenha os ombros estabilizados", "Não arquee excessivamente as costas", "Controle a descida por 2 segundos"]'::jsonb),
  ('Crucifixo com Halteres', 'peito', 'intermediario', 'Excelente para alongamento e definição do peitoral', '["halteres", "banco"]'::jsonb, '30-45min', 3, '12-15', 45, '["Deite-se no banco com halteres acima do peito", "Com cotovelos levemente flexionados, abra os braços", "Desça até sentir alongamento no peitoral", "Retorne à posição inicial contraindo o peito"]'::jsonb, '["Mantenha uma leve flexão nos cotovelos", "Não desça demais para evitar lesões", "Foque na contração do peitoral"]'::jsonb),
  ('Remada com Halter', 'costas', 'iniciante', 'Desenvolve espessura das costas', '["halteres", "banco"]'::jsonb, '40-55min', 4, '8-12', 60, '["Apoie joelho e mão no banco", "Segure o halter com braço estendido", "Puxe o halter em direção ao tronco", "Mantenha as costas retas durante o movimento"]'::jsonb, '["Mantenha o core contraído", "Puxe com o cotovelo, não com a mão", "Evite rodar o tronco"]'::jsonb),
  ('Barra Fixa', 'costas', 'intermediario', 'Exercício completo para desenvolvimento das costas', '["barra"]'::jsonb, '35-50min', 3, '6-10', 90, '["Segure a barra com pegada pronada", "Pendure-se com braços estendidos", "Puxe o corpo até o queixo passar da barra", "Desça controladamente"]'::jsonb, '["Mantenha o peito aberto", "Evite balançar o corpo", "Foque em puxar com as costas"]'::jsonb),
  ('Agachamento Livre', 'pernas', 'iniciante', 'Exercício completo para membros inferiores', '["peso corporal"]'::jsonb, '50-65min', 4, '12-15', 90, '["Pés na largura dos ombros", "Desça como se fosse sentar", "Mantenha coluna ereta e peito aberto", "Volte à posição inicial contraindo glúteos"]'::jsonb, '["Joelhos alinhados com os pés", "Não deixe os joelhos ultrapassarem os pés", "Mantenha o peso nos calcanhares"]'::jsonb),
  ('Leg Press', 'pernas', 'iniciante', 'Fortalece quadríceps e glúteos com segurança', '["leg press"]'::jsonb, '45-60min', 4, '10-12', 75, '["Posicione os pés na plataforma", "Destrave a máquina", "Desça até formar 90 graus nos joelhos", "Empurre com os calcanhares"]'::jsonb, '["Mantenha a lombar apoiada", "Não trave os joelhos no topo", "Controle a descida"]'::jsonb),
  ('Desenvolvimento com Halteres', 'ombros', 'iniciante', 'Desenvolve força e volume dos ombros', '["halteres"]'::jsonb, '40-50min', 3, '10-12', 60, '["Sente-se com halteres na altura dos ombros", "Empurre os halteres para cima", "Estenda os braços completamente", "Desça controladamente"]'::jsonb, '["Mantenha o core contraído", "Não arquee as costas", "Controle o movimento"]'::jsonb),
  ('Rosca Direta', 'biceps', 'iniciante', 'Exercício clássico para bíceps', '["halteres"]'::jsonb, '30-40min', 3, '10-12', 45, '["Fique em pé com halteres nas mãos", "Mantenha cotovelos junto ao corpo", "Flexione os braços elevando os halteres", "Desça controladamente"]'::jsonb, '["Não balance o corpo", "Mantenha os cotovelos fixos", "Controle a descida"]'::jsonb),
  ('Tríceps Testa', 'triceps', 'intermediario', 'Exercício eficaz para tríceps', '["barra", "banco"]'::jsonb, '35-45min', 3, '10-12', 60, '["Deite-se no banco segurando a barra", "Desça a barra em direção à testa", "Mantenha cotovelos fixos", "Estenda os braços completamente"]'::jsonb, '["Mantenha os cotovelos fixos", "Não abra os cotovelos", "Controle o movimento"]'::jsonb),
  ('Elevação Pélvica', 'gluteos', 'iniciante', 'Fortalece e tonifica os glúteos', '["peso corporal"]'::jsonb, '30-40min', 3, '15-20', 45, '["Deite-se de costas com joelhos flexionados", "Eleve o quadril contraindo os glúteos", "Mantenha no topo por 2 segundos", "Desça controladamente"]'::jsonb, '["Contraia os glúteos no topo", "Não arquee demais as costas", "Mantenha o core ativo"]'::jsonb),
  ('Abdominal Supra', 'abdomen', 'iniciante', 'Fortalece a região superior do abdômen', '["peso corporal"]'::jsonb, '20-30min', 3, '15-20', 30, '["Deite-se de costas com joelhos flexionados", "Coloque as mãos atrás da cabeça", "Eleve o tronco contraindo o abdômen", "Desça controladamente"]'::jsonb, '["Não puxe o pescoço", "Mantenha o queixo afastado do peito", "Expire na subida"]'::jsonb),
  ('Corrida Intervalada', 'cardio', 'intermediario', 'Treino cardiovascular de alta intensidade', '["esteira"]'::jsonb, '30-45min', 8, '1-2 min', 120, '["Aqueça por 5 minutos em ritmo leve", "Alterne 1 min forte com 2 min leve", "Repita por 20-30 minutos", "Esfrie por 5 minutos"]'::jsonb, '["Mantenha boa postura", "Respire ritmadamente", "Hidrate-se adequadamente"]'::jsonb),
  ('Adução de Pernas', 'adutores', 'iniciante', 'Fortalece a parte interna das coxas', '["máquina adutora"]'::jsonb, '25-35min', 3, '12-15', 45, '["Sente-se na máquina adutora", "Posicione as pernas nas almofadas", "Junte as pernas contraindo os adutores", "Volte controladamente"]'::jsonb, '["Mantenha as costas apoiadas", "Não use impulso", "Controle o movimento"]'::jsonb);